cloud:
  aws:
    s3:
      bucket: bucket-name
    credentials:
      instanceProfile: true
    stack:
      auto: false

spring:
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MySQL
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    show_sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        highlight_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

file:
  common:
    domain: https://domain.com
    root: root/
    directory: directory/
