name: CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ip-172-31-3-169

    steps:
      - name: 배포 스크립트 실행
        run: |
          cd
          sudo sh deploy.sh
        working-directory: ${{ env.working-directory }}
